app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
db/migrate/20171121193209_add_name_to_users.rb
db/schema.rb

-UI for Login and Sign up Improved
-User Schema edited, now includes first and last names
-migration created to handle the schema changes

Improved UI interface for Login and Sign Up

---

app/controllers/profiles_controller.rb
app/views/profiles/edit_profile.html.erb
config/routes.rb

Just set up the route and controller for user profile

Opened the rout to updating dashboard

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/listings_controller.rb
app/policies/application_policy.rb
app/policies/booking_policy.rb
app/policies/listing_policy.rb
test/policies/booking_policy_test.rb
test/policies/listing_policy_test.rb

Added pundit.Pundit added only to a) application file; b) booking file; c) listing file. I don't believe we need it anywhere else.
@mit1812  may not be bad if you give it a look before approving? You are the expert :).

added pundit to icancook

---

app/controllers/profiles_controller.rb

forgot to save

---

app/controllers/pages_controller.rb
app/controllers/profiles_controller.rb
app/policies/user_policy.rb
app/views/pages/dashboard.html.erb
app/views/profiles/edit_profile.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

Just set up the route, view, action for dashboard (aka profile). 
I will work on the design of the view now SEPARATELY, did not want to wait too long to commit.

added dashboard (aka profile)

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/listings/_index.scss
app/assets/stylesheets/listings/_listing-new.scss
app/controllers/listings_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/views/layouts/application.html.erb
app/views/listings/new.html.erb
db/migrate/20171122152531_remove_and_change_to_listings_table.rb
db/schema.rb
package.json
yarn.lock

-Form created in listing new
-Pending Cool CSS for the form 
-Radio buttons for the types of events

Created a form for listing

---

db/migrate/20171122172846_remove_and_add_column_to_listings.rb
db/schema.rb
package-lock.json
package.json
yarn.lock

-Events is now an array so it can store the results of multiple checkboxes
-JS for checkboxes still pending..

Changed the events column into an array

---

app/controllers/listings_controller.rb

-Index can be viewed by anyone visiting the site without the requirement of logging in

Lifted off login restrictions for viewing all cooks

---

app/views/listings/show.html.erb

- Modified the map code to add the correct markers when valid address details are entered

Completed added marker to the map

---

app/assets/stylesheets/listings/_listing-new.scss
app/controllers/listings_controller.rb
app/policies/listing_policy.rb
app/views/listings/new.html.erb
config/initializers/simple_form.rb
db/schema.rb

Fixed Search by date to work with multiple dates if user has multiple availabilities.

Search works with multiple Dates Now and Corrected the Listings Form

---

app/views/listings/show.html.erb

Added the key for static Google Map for the marker to work now

Added Key for Static Map

---

app/javascript/plugins/flatpickr.js
app/views/pages/home.html.erb

- Date search on home page is now more dynamic through the use of Javascript

Added JS For date picker on Home Search

---

app/assets/stylesheets/listings/_listing-new.scss
app/views/listings/new.html.erb

-Improved the UI of Listings form for betters user experience
-It is also responsive dependant on the type of screen the user is viewing on

Improved the UI of Listings Form

---

app/views/shared/_navbar.html.erb

When on Mobile and user is not logged in they have the option to Sign in or Sign Up now.

Added Sign In and Sign Up to the Mobile Navbar dropdown

---

app/assets/stylesheets/components/_footer.scss
app/views/shared/_footer.html.erb

Footer is now ready to be pushed to production

Footer now created, edited and has relevant content added

---

app/assets/stylesheets/payments/_new.scss
app/views/payments/new.html.erb

Created a beautiful booking form with awesome UX Design

Completed created a booking with UX Design for it

---

app/views/devise/registrations/edit.html.erb

Fixed UI for Users Edit Pgae

---

app/assets/stylesheets/conversations/conversation-index.scss
app/assets/stylesheets/listings/_listing-index.scss
app/views/conversations/index.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/listings/index.html.erb
app/views/messages/index.html.erb

Footer issue fixed. Its now sticking to the bottom of the pages

Fixed footer issue on multiple pages

---

app/assets/stylesheets/listings/_listing-index.scss
app/assets/stylesheets/payments/_new.scss
app/views/layouts/application.html.erb
app/views/payments/new.html.erb

Footer Issue is fixed for payments page
Og:Image changed to img_url

Fixed footer issue on payments page

---

app/assets/stylesheets/listings/_listing-index.scss
app/views/listings/index.html.erb

Fixed the responsiveness of the cooks results. They should appear responsive for all display types now.

Fixed display issues with cooks results

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Search boxes now remain responsive on all devices now.

Search on Homepage is now more responsive on all device types

---

app/assets/stylesheets/pages/_home.scss

The search bar on home page is now responsive with the use of grid for all mobile devices

Added Grid Layout for the search boxes on homepage

---

app/views/listings/index.html.erb

Listings page is now more responsive for mobile devices

Listings Page is reponsive for mobile devices

---

app/assets/stylesheets/listings/_listing-index.scss
app/views/listings/index.html.erb

Responsive for iPad pro and larger displays such as laptops or desktops or TV screens

Responsive on Desktops aswell for listings now
